const APP_ACTION_TYPE = {
  HANDLE_LIST_STORE_FETCH: 'HANDLE_LIST_STORE_FETCH',
  HANDLE_LIST_STORE_FETCH_SUCCESS: 'HANDLE_LIST_STORE_FETCH_SUCCESS',
  HANDLE_STORE_FETCH: 'HANDLE_STORE_FETCH',
  HANDLE_STORE_FETCH_SUCCESS: 'HANDLE_STORE_FETCH_SUCCESS',
  EDIT_STORE_PROFILE: 'EDIT_STORE_PROFILE',
  EDIT_STORE_PROFILE_SUCCESS: 'EDIT_STORE_PROFILE_SUCCESS',
};
export default APP_ACTION_TYPE;

